//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj.AspNetMVC.StokTakip.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciRoller
    {
        public int Id { get; set; }
        public int KullaniciId { get; set; }
        public int RolId { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Roller Roller { get; set; }
    }
}
