//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj.AspNetMVC.StokTakip.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int Id { get; set; }
        public int KullaniciId { get; set; }
        public int UrunId { get; set; }
        public decimal BirimFiyati { get; set; }
        public decimal Miktari { get; set; }
        public decimal ToplamFiyati { get; set; }
        public System.DateTime Tarih { get; set; }
        public System.DateTime Saat { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
